#!/usr/bin/env node
"use strict";

var Translator = require("./src/translator.js").Kuma.Translator,
    Parser = require("./src/parser.js").Kuma.Parser,
    Scanner = require("./src/parser.js").Kuma.Scanner,
    Core = require("./src/runtime.js").Kuma.Core,
    fs = require('fs'),
    readline = require('readline'),
    Kuma = {
        "Core": Core
    };
var optimist = require('optimist')
    .usage('Usage: $0 -e eval')
    .alias('h', 'help').describe('h', 'show this help message')
                       .describe('dump_ast', 'dump abstract syntax tree')
                       .describe('dump_token', 'dump tokens')
    .alias('D', 'dump_js')
        .describe('dump_js',  'dump translated javascript source code')
        .boolean('D')
    ;
var argv = optimist.argv;

if (argv.h) {
    console.log(optimist.help());
    process.exit(0);
}

if (argv.e) {
    // -e  means eval mode
    var src = '' + argv.e;
    global.ARGV = argv._;
    evaluate.call(this, src);
} else if (argv._.length > 0) {
    var fname = argv._[0];
    var src = fs.readFileSync(fname, 'utf-8');
    global.ARGV = argv._.slice(1);
    evaluate.call(this, src);
} else {
    global.ARGV = argv._;

    // TODO: readline?
    var rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    rl.setPrompt('~> ');
    rl.prompt();
    rl.on('line', function(src) {
        try {
            console.log(evaluate.call(this, ''+src.trim()));
        } catch (e) { console.log(e); }
        rl.prompt();
    }).on('close', function () {
        process.exit(0);
    });
}

function evaluate(src) {
    var parser = new Parser(src);
    if (argv.dump_token) {
        console.log(parser.tokens);
    }
    var ast = parser.parse();
    if (argv.dump_ast) {
        console.log(JSON.stringify(ast));
    }
    var translator = new Translator();
    var js = translator.translate(ast);
    if (argv.dump_js) {
        console.log(js);
    }
    return eval(js);
}

